from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib import colors
from datetime import datetime
from PIL import Image as PILImage
import os, textwrap

def _fit_image(img_path: str, max_w: float, max_h: float):
    with PILImage.open(img_path) as im:
        w, h = im.size
    r = min(max_w / w, max_h / h)
    return max(1, w * r), max(1, h * r)

def _draw_header(c: canvas.Canvas, page_w: float, page_h: float, title: str, organization: str, logo_path: str | None):
    bar_h = 1.5 * cm
    c.setFillColor(colors.HexColor("#0F172A"))
    c.rect(0, page_h - bar_h, page_w, bar_h, fill=1, stroke=0)

    x = 1.6 * cm
    if logo_path and os.path.exists(logo_path):
        try:
            c.drawImage(logo_path, x, page_h - bar_h + 0.25*cm, width=1.1*cm, height=1.1*cm, mask='auto', preserveAspectRatio=True)
        except Exception:
            pass
        x += 1.4 * cm

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x, page_h - bar_h + 0.6*cm, title)

    if organization:
        c.setFont("Helvetica", 9.5)
        txt = organization
        tw = c.stringWidth(txt, "Helvetica", 9.5)
        c.drawString(page_w - 1.6 * cm - tw, page_h - bar_h + 0.62*cm, txt)

def _draw_footer(c: canvas.Canvas, page_w: float):
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#64748B"))
    disclaimer = "This report is generated by an AI-assisted tool and must be reviewed by a qualified clinician."
    c.drawString(1.6*cm, 1.5*cm, disclaimer)
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%SZ")
    tw = c.stringWidth(ts, "Helvetica", 8)
    c.drawString(page_w - 1.6*cm - tw, 1.5*cm, ts)

def _boxed(c: canvas.Canvas, x: float, y_top: float, w: float, h: float, title: str):
    c.setStrokeColor(colors.HexColor("#CBD5E1"))
    c.setLineWidth(1.1)
    c.roundRect(x, y_top - h, w, h, 0.35*cm, stroke=1, fill=0)
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.HexColor("#0F172A"))
    c.drawString(x + 0.5*cm, y_top - 0.8*cm, title)

def _kv(c: canvas.Canvas, x: float, y: float, k: str, v: str):
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#475569"))
    c.drawString(x, y, f"{k}:")
    c.setFillColor(colors.HexColor("#0F172A"))
    c.drawString(x + 3.6*cm, y, v)


def generate_report(
    path: str,
    *,
    patient_name: str,
    doctor_name: str,
    mrn: str,
    image_name: str,
    result: str,
    prob: float,
    image_path: str | None = None,
    heatmap_path: str | None = None,
    organization: str | None = "NeuroScan Imaging",
    logo_path: str | None = None
):
    c = canvas.Canvas(path, pagesize=A4)
    page_w, page_h = A4

    # Header
    _draw_header(c, page_w, page_h, "Brain MRI Tumor Detection Report", organization or "", logo_path)

    # Patient Box
    top = page_h - 2.2*cm
    box_h = 5.4*cm
    _boxed(c, 1.5*cm, top, page_w - 3.0*cm, box_h, "Patient & Study Information")

    y = top - 1.6*cm
    _kv(c, 2.0*cm, y, "Patient", patient_name);           y -= 0.7*cm
    _kv(c, 2.0*cm, y, "MRN", mrn);                        y -= 0.7*cm
    _kv(c, 2.0*cm, y, "Referring Doctor", doctor_name);   y -= 0.7*cm
    _kv(c, 2.0*cm, y, "Source Image", image_name);        y -= 0.7*cm

    _kv(c, 2.0*cm, y, "Prediction", result.capitalize())
    y -= 0.7*cm
    _kv(c, 2.0*cm, y, "Probability", f"{prob*100:.1f}%")
    y -= 1.2*cm  # safe spacing before next box


    # Imaging Box
    box2_top = top - box_h - 1.0*cm
    box2_h = 11.5*cm
    _boxed(c, 1.5*cm, box2_top, page_w - 3.0*cm, box2_h, "Imaging Evidence")

    inner_x = 1.5*cm + 0.7*cm
    inner_w = (page_w - 3.0*cm) - 1.4*cm
    gap = 0.8*cm
    col_w = (inner_w - gap) / 2.0
    max_h = box2_h - 2.4*cm

    # Original image
    if image_path and os.path.exists(image_path):
        w, h = _fit_image(image_path, col_w, max_h)
        x = inner_x
        y_img = box2_top - 1.4*cm - h
        c.drawImage(image_path, x, y_img, width=w, height=h, mask='auto', preserveAspectRatio=True)
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(x, y_img - 0.4*cm, "Original MRI")

    # Heatmap overlay
    x2 = inner_x + col_w + gap
    if heatmap_path and os.path.exists(heatmap_path):
        w2, h2 = _fit_image(heatmap_path, col_w, max_h)
        y2 = box2_top - 1.4*cm - h2
        c.drawImage(heatmap_path, x2, y2, width=w2, height=h2, mask='auto', preserveAspectRatio=True)
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(x2, y2 - 0.4*cm, "AI Attention (Grad-CAM)")
    else:
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.HexColor("#DC2626"))
        c.drawString(x2, box2_top - 1.8*cm, "Heatmap unavailable for this scan.")

    # Note
    note_y = box2_top - box2_h - 0.6*cm
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#0F172A"))
    note = ("The AI heatmap highlights areas that most influenced the model’s decision. "
            "It is not a segmentation and should be correlated with clinical context.")
    for line in textwrap.wrap(note, width=110):
        c.drawString(1.6*cm, note_y - 0.4*cm, line)
        note_y -= 0.45*cm

    _draw_footer(c, page_w)
    c.showPage()
    c.save()
